#!/bin/bash

#validation of script arguments
if [[ $# -eq 0 || $# -gt 10 || $# -lt 10 ]] ; then
   printf " Error: %d arguments entered, Plese provide in proper syntax ./runCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>\n" "$#"
   exit 0
elif [ ! -f ${10} ] ; then
   printf "The given keyfile doesnot exists so aborting the script\n"
   exit 0
fi

# Information of all replica servers list
HOSTS_LIST=(ec2-54-210-1-206.compute-1.amazonaws.com                
ec2-54-67-25-76.us-west-1.compute.amazonaws.com         
ec2-35-161-203-105.us-west-2.compute.amazonaws.com      
ec2-52-213-13-179.eu-west-1.compute.amazonaws.com       
ec2-52-196-161-198.ap-northeast-1.compute.amazonaws.com 
ec2-54-255-148-115.ap-southeast-1.compute.amazonaws.com 
ec2-13-54-30-86.ap-southeast-2.compute.amazonaws.com    
ec2-52-67-177-90.sa-east-1.compute.amazonaws.com        
ec2-35-156-54-135.eu-central-1.compute.amazonaws.com 
)

#SYNTAX of the script: ./[deploy|run|stop]CDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>

# Performing the execution of DNS server
echo "DNS server  is started...."
ssh -i ${10} $8@cs5700cdnproject.ccs.neu.edu "chmod 755 dnsserver"
ssh -i ${10} $8@cs5700cdnproject.ccs.neu.edu "./dnsserver -p $2 -n $6 < /dev/null > ./logfile 2>&1 &"

# Performing the execution of HTTP replica servers in all hosts
for host in "${HOSTS_LIST[@]}"
do
  echo "HTTP server is running in HOST $host..."
  ssh -i ${10} $8@${host} "chmod 755 httpserver.py"
  ssh -i ${10} $8@${host} "./httpserver -p $2 -o $4 < /dev/null > ./logfile 2>&1 &"
done
